repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.3 
  hooks:
    - id: terraform_fmt
    # - id: terraform_validate
    - id: terraform_docs
      args: 
        - --hook-config=--path-to-file=README.md        
        - --hook-config=--add-to-existing-file=true     
        - --hook-config=--create-file-if-not-exist=true 
    - id: terraform_tflint
      args:
        - --args=--config="__GIT_WORKING_DIR__/02-Terraform-AKSCluster/.tflint.hcl" 

    - id: terraform_trivy
      args:
        - --args=--skip-dirs="./kubernetes-*" 
        - --args=--severity=HIGH,MEDIUM --quiet
        - --args=--tf-vars="__GIT_WORKING_DIR__/02-Terraform-AKSCluster/terraform.tfvars" 

    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--skip-check CKV2_AWS_8
        - --args=--framework terraform
        - --args=--directory .
        - --args=--check MEDIUM  # Require API

