repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.3 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
        - --hook-config=--use-standard-markers=true  
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/02-Terraform-AKSCluster/.tflint.hcl   # Boolean. Defaults to true (v1.93+), false (<v1.93). Set to true for compatibility with terraform-docs


# repos:
#   - repo: https://github.com/pre-commit/mirrors-terrafmt
#     rev: v0.23.0  # Specify the version to use
#     hooks:
#       - id: terraform_fmt
#         files: \.tf$

#   - repo: https://github.com/terraform-linters/tflint
#     rev: v0.40.0  # Specify the version to use
#     hooks:
#       - id: tflint
#         files: \.tf$

#   - repo: https://github.com/terraform-linters/terraform-docs
#     rev: v0.16.0  # Specify the version to use
#     hooks:
#       - id: terraform-docs
#         files: \.tf$

#   - repo: https://github.com/terraform-linters/tfsec
#     rev: v1.21.0  # Specify the version to use
#     hooks:
#       - id: tfsec
#         files: \.tf$
